obstacle_range: 3.5
raytrace_range: 4.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.25
inflation_radius: 0.2

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera_depth_frame, data_type: PointCloud2, topic: /camera/depth_registered/points_filtered, marking: true, clearing: true}
