global_costmap:
  width: 100
  height: 100
  origin_x: -50
  origin_y: -50
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 2.0
  static_map: true
  rolling_window: false
  resolution: 0.1
  publish_frequency: 0.5
